services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Server@123456
            - MSSQL_PID=Express
        volumes:
            - sql-data:/var/opt/mssql
        ports:
            - "1433:1433"
        networks:
            - app-network
        expose:
            - "1433"

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile

        environment:
            ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Initial Catalog=HappyWedding;User ID=SA;Password=Server@123456;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False;"
            ASPNETCORE_URLS: "http://0.0.0.0:8080"
        depends_on:
            - sqlserver
        networks:
            - app-network
        # deploy:
        #   replicas: 1
        #   restart_policy:
        #     condition: on-failure
        ports:
            - "8080:8080"

        command: >
          /bin/sh -c "
            dotnet ef database update &&
            dotnet server.dll"

    frontend:
        build:
            context: ./www
            dockerfile: Dockerfile

        environment:
            # - REACT_APP_API_URL=http://backend/api
            - REACT_APP_API_URL=http://localhost:8080/api
            - REACT_APP_BASE_URL=http://localhost:8080
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - app-network

    proxy:
        image: nginx:latest
        hostname: proxy.HappyWedding
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - frontend
        networks:
            - app-network

volumes:
    sql-data:

networks:
    app-network:
        # driver: overlay
        driver: bridge
